apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 5worlds-com-tls
spec: 
  secretName: 5worlds-com
  issuerRef:  
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 5worlds.com
  dnsNames: 
    - 5worlds.com
    - www.5worlds.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - 5worlds.com
          - www.5worlds.com